Landingpage erstellt
muhanad-musawi/die-karte pull request #29
Opened 2022-11-10 14:51 UTC by muhanad-musawi

2022-11-10 15:14 UTC, fabiandarga requested changes

2022-11-10 15:14 UTC, fabiandarga commented on src/components/button/Button.jsx
> +    className = 'landingpageBTN';
Das finde ich nicht gut. **Variant** ist dafür da den Basis-Button leicht anzupassen, z.B. verschiedene Farb-Themes (primary, secondary, alert, etc.. wie in bootstrap.) für andere Eigenschaften kann man neue props hinmzufügen, z.B. hideBorder="true", fullWidth="true" für 100% breite und so weiter.
Im besten Fall kann man mit diesem "Werkzeugkasten" dann alle Buttons auf der Seite machen.
Wenn jedoch Buttons dabei sind, die sich so stark von der Basisvariante unterscheiden, das es mit Theme und Eigenschaften nicht reicht, dann sollte eine neue Button-Komponente erstellt werden.

2022-11-10 15:14 UTC, fabiandarga commented on src/components/button/button.scss
> +}
Die Varianten sollten nicht so viele css Eigenschaften überschreiben. Siehe anderer Kommentar

2022-11-10 15:14 UTC, fabiandarga commented on src/components/landingPageForm/LandingPageForm.jsx
> +          <div className="inputFieldFirstAndLastName">
Diese Klasse kann weg, wird nirgendwo benutzt

2022-11-10 15:14 UTC, fabiandarga commented on src/components/landingPageForm/LandingPageForm.jsx
> +          <div className="inputFieldsEmailAndnumber">
Diese Klasse kann weg, wird nirgendwo benutzt

2022-11-10 15:14 UTC, fabiandarga commented on src/components/landingPageForm/LandingPageForm.jsx
> +        <Button type="submit" variant="landingpageBTN" disabled={state.submitting}>
Hier würe es schön wenn hier z.B. sowas stehen würde: `<Button variant="red-outline" size="lg" />`

2022-11-10 15:14 UTC, fabiandarga commented on src/components/landingpageHeader/landingpageHeader.scss
> +    padding: 0;
hatten wir nicht irgendwo ein resett css? Eigentlich soltlen ja alle Elemente margin und padding = 0 haben

2022-11-10 15:14 UTC, fabiandarga commented on src/pages/landingpage/landingpage.scss
> +    .landingpageBody  {
Diese Klasse hat keine eigenen Styles, nur die Kinder. Deshalb kannst du die Ebene auch weglöschen.
Das sorgt nur für unnötig spezifische selektoren im css:
Sowas steht nachher im output css: `.landingpageContent .landingpageBody .carousel {`
Dabei reicht das hier:
`.landingpageContent .carousel {`

2022-11-13 12:13 UTC, muhanad-musawi commented on src/components/landingPageForm/LandingPageForm.jsx
> +          <div className="inputFieldFirstAndLastName">
Die Klasse wird benutzt

2022-11-13 12:14 UTC, muhanad-musawi commented on src/components/landingPageForm/LandingPageForm.jsx
> +          <div className="inputFieldsEmailAndnumber">
die klasse wird auch benutzt aber nicht bei landingpage.scss

2022-11-14 16:23 UTC, fabiandarga requested changes

2022-11-14 16:23 UTC, fabiandarga commented on src/components/LandingpageCarousel/landingpageCarousel.scss
> +.carouselCntent {
Klassenname falsch? `Cntent` -> `Content`

2022-11-14 16:23 UTC, fabiandarga commented on src/components/LandingpageCarousel/landingpageCarousel.scss
> +  @media (min-width: 800px) {
Du hast hier zweimal 800px benutzt. Wahrscheinlich nicht absichtlich

2022-11-14 16:23 UTC, fabiandarga commented on src/components/landingPageForm/LandingPageForm.jsx
> +        <p>Danke fürs Kontaktieren, wir melden uns schnellstmöglich bei ihnen!</p>
`Ihnen` großschreiben

2022-11-14 16:23 UTC, fabiandarga commented on src/pages/landingpage/Landingpage.jsx
> +            Interessieren sie sich für eine digitale Speisekarte, so kontaktieren sie uns gerne für
```suggestion
            Interessieren Sie sich für eine digitale Speisekarte, dann kontaktieren Sie uns gerne für
```

2022-11-15 09:12 UTC, merged